### {{names(map.plots.regions[[i]]$map_plot[j])}}

```{r country-plots-{{i}}-regions-{{names(map.plots.regions[[i]]$map_plot[j])}}, fig.align='center', fig.width=6, echo = FALSE, warning=FALSE}
  # wanted to have chunk names with country names but it doesn't work with cote d'ivoire
  country = "{{names(map.plots.regions[i])}}"
  region = "{{names(map.plots.regions[[i]][['map_plot']][j])}}"
  #print(region)
  # try separate.. need to align them
  cases = map.plots.regions[[country]]$cases
  crop_plot = map.plots.regions[[country]][['crop_plots']][[region]][[1]]
  # adjust legend
  cases = cases + theme(legend.position = "top", legend.spacing = unit(0.5, 'cm'), legend.key.width = unit(0.4, "cm")) + guides(color=guide_legend(nrow=3)) # ,label.position = "bottom"
  # #cases
  # remove title from crop_plot
  #crop_plot = crop_plot + theme(plot.title = element_blank())
  # with plot grid
  together <- plot_grid(cases, crop_plot, ncol=1, align="v", rel_heights = c(2, 1))
  # together
  grid.arrange(together)
  
```

```{r country-maps-{{i}}-regions-{{names(map.plots.regions[[i]]$map_plot[j])}}, results='asis', fig.width=6, fig.align = 'center', echo = FALSE}
  country = "{{names(map.plots.regions[i])}}"
  region = "{{names(map.plots.regions[[i]][['map_plot']][j])}}"
  #print(region)
  # these are the country region maps
  # the actual maps
  grid.arrange(map.plots.regions[[country]][['map_plot']][[region]])
```
