
## {{names(combined.plots[i])}} 

```{r country-plots-{{names(combined.plots[i])}}, fig.align='center', fig.width=9, fig.height=9, echo = FALSE, warning = FALSE}
  country = "{{names(combined.plots[i])}}"
  # try separate.. need to align them
  cases = combined.plots[[country]][['cases']]
  crop_plot = combined.plots[[country]][['crop_plot']][[1]]
  # adjust legend
  cases = cases + theme(legend.position = "top", legend.spacing = unit(0.5, 'cm'), legend.key.width = unit(0.4, "cm")) + guides(color=guide_legend(nrow=4)) # ,label.position = "bottom"
  # remove title from crop_plot
  crop_plot = crop_plot + theme(plot.title = element_blank())
  # increase axis label sizes
  crop_plot = crop_plot + theme(axis.text.x = element_text(angle=90, size=12))
  cases = cases + theme(axis.text.x = element_text(angle=90, size=12))
  # increase legend font size
  cases = cases + theme(legend.text = element_text(size=10))
  # with plot grid
  together <- plot_grid(cases, crop_plot, ncol=1, align="v", rel_heights = c(3, 1.5))
  together
```

```{r country-maps-{{names(combined.plots[i])}}, fig.align = 'center', echo = FALSE, results='asis', out.width='50%'}
  # fig.width=3.7,
  # these are the country maps
  country = "{{names(combined.plots[i])}}"
  # the actual maps
  grid.arrange(combined.plots[[country]][['map_plot']][[1]])
  #cat("  \n")
```
