require(qs)
require(lubridate)
require(ggplot2)
require(scales)
require(data.table)
require(lubridate)
require(reshape2)
require(cowplot)
require(grid)
require(tidyquant)
require(grImport)
require(gridExtra)
# maybe don't need all these - decide later
#require(magick)
#require(tiff)
#require(raster)
#require(rgdal)
#require(ggplotify)
require(png)
require(knitr)
require(rmarkdown)
require(pander)
require(haven)
require(kableExtra)
# until we have png map files
# require(maps)
# require(mapdata)
# require(dplyr)
# require(sf)
# library(rgdal)
# library(maptools)
library(raster)
# require(dplyr)